### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError when using high dimension images as icons

### ISSUE THREAD

**Issue by virtumonde** [react-native-mapbox-gl/maps#1005]
**Description**
```Fatal Exception: java.lang.OutOfMemoryError``` is invoked and the app crashes when high dimension images are used in production (in debug mode some of the images turn gray).

**To Reproduce**
1) Create a map
2) Add 500+ points with icons that are 512x512px (about 12 different icons).
3) Run the release version on a real device (tested only on Android)
4) Get ```Fatal Exception: java.lang.OutOfMemoryError```

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 33693708 byte allocation with 16777216 free bytes and 27MB until OOM
       at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:54)
       at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:49)
       at java.nio.ByteBuffer.allocate(ByteBuffer.java:261)
       at com.mapbox.mapboxsdk.maps.Style.toImage(Style.java:1058)
       at com.mapbox.mapboxsdk.maps.Style.addImages(Style.java:402)
       at com.mapbox.mapboxsdk.maps.Style.addImages(Style.java:388)
       at com.mapbox.rctmgl.utils.DownloadMapImageTask.onPostExecute(DownloadMapImageTask.java:141)
       at com.mapbox.rctmgl.utils.DownloadMapImageTask.onPostExecute(DownloadMapImageTask.java:40)
       at android.os.AsyncTask.finish(AsyncTask.java:667)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6228)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 37748748 byte allocation with 16777216 free bytes and 17MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
       at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:478)
       at com.mapbox.rctmgl.utils.BitmapUtils.getBitmapFromResource(BitmapUtils.java:64)
       at com.mapbox.rctmgl.utils.DownloadMapImageTask.doInBackground(DownloadMapImageTask.java:119)
       at com.mapbox.rctmgl.utils.DownloadMapImageTask.doInBackground(DownloadMapImageTask.java:40)
       at android.os.AsyncTask$2.call(AsyncTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Versions (please complete the following information):**
 - Platform: Android
 - Device: ZTE Blade
 - Emulator: no
 - react-native-mapbox-gl version: 8.1.0-rc.2
 - React Native Version 0.63.2

**Comment by virtumonde** [comment]
Is there a way to make this library work in this scenario?

**Comment by virtumonde** [comment]
The obvious fix is to reduce the size of the images, which worked. Are there other options?

**Comment by Beamanator** [comment]
@virtumonde did you try adding `android:largeHeap="true"` to the `application` tag in `android/app/src/main/AndroidManifest.xml`?

I ran into the same error you did, made the above change (after seeing this issue: https://github.com/facebook/react-native/issues/6799) and the error went away, at least for the few devices I've tested so far.

**Comment by virtumonde** [comment]
@Beamanator that unfortunately did not help, only reducing the image size solved the problem.
