### ISSUE TITLE
[Android] Kitkat 4.4 api 19 crashes

### ISSUE THREAD

**Issue by aless10** [react-native-mapbox-gl/maps#1116]
Hi all,
I'm having some issues to run my application on android kitkat 4.4 api version 19. 
Unfortunately, I cannot test it on a physical device but I only tested it with the emulator created in android studio.
The bug: whenever I try to run the app in debug mode, the app crashes.
This is the error log
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 2133
    java.lang.RuntimeException: Unable to get provider com.mapbox.android.telemetry.provider.MapboxTelemetryInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.android.telemetry.provider.MapboxTelemetryInitProvider" on path: DexPathList[[zip file "/data/app/com.myapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.myapp-1, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.android.telemetry.provider.MapboxTelemetryInitProvider" on path: DexPathList[[zip file "/data/app/com.myapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.myapp-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
```
I think that this is something related to this https://stackoverflow.com/questions/56044314/how-to-fix-java-lang-runtimeexception-unable-to-get-provider-com-mapbox-andro/56794861

```js
import MapboxGL, { OnPressEvent } from '@react-native-mapbox-gl/maps'
const MapboxMap = styled(MapboxGL.MapView)`
  width: ${Dimensions.get('window').width}px
  height: ${Dimensions.get('window').height}px
`

function MapScreenComponent() {
  const map = useRef<MapboxGL.MapView>()
  const camera = useRef<MapboxGL.Camera>()

  useEffect(() => {
    mapState.setMapboxCamera(camera)
    mapState.setMapboxMap(map)
  }, [])

  function clickOnMarker(e: OnPressEvent) {
    const [lng, lat] = [e.coordinates.longitude, e.coordinates.latitude]
    const isCluster = e.features.some((f) => f.properties.cluster)
    if (isCluster) return mapState.flyAndZoomTo([lng, lat])
    const userCoords = { lat: 45.488485, lng: 9.215617 }
    retrieveDirections(userCoords, { lng, lat }).then((directions) => {
      const route = directions?.routes[0]
      if (!route) return
      mapState.setRoute(route)
    })
  }

  return (
    <Container>
      <SearchBar>
        <MapSearchBar></MapSearchBar>
      </SearchBar>
      <MapboxMap
        ref={map}
        userTrackingMode={MapboxGL.UserTrackingModes.Follow}
        onRegionDidChange={mapState.updateClusters}
        styleURL={MAP_STYLE_URL}
      >
        <MapboxGL.Camera
          zoomLevel={INITIAL_REGION.zoomLevel}
          ref={camera}
          centerCoordinate={[INITIAL_REGION.lon, INITIAL_REGION.lat]}
        />
        {deviceState.lat !== null && deviceState.lon !== null && (
          <MapboxGL.PointAnnotation
            id="user"
            title="user"
            coordinate={[deviceState.lon, deviceState.lat]}
          >
            <UserMarker source={require('../assets/images/app-logo.png')} />
          </MapboxGL.PointAnnotation>
        )}

        {mapState.route ? (
          <MapboxGL.ShapeSource id="directions" shape={mapState.route.geometry}>
            <MapboxGL.LineLayer
              id="directionsLine"
              style={{ lineColor: 'blue', lineWidth: 3, lineDasharray: [3, 3] }}
            />
          </MapboxGL.ShapeSource>
        ) : null}

        <MapboxGL.ShapeSource
          id="symbolLocationSource"
          hitbox={{ width: 18, height: 18 }}
          onPress={clickOnMarker}
          shape={{ type: 'FeatureCollection', features: mapState.clusters }}
        >
          <MapboxGL.SymbolLayer
            id="pointCount"
            maxZoomLevel={14}
            style={{
              textField: '{point_count}',
              textSize: 10,
              textColor: '#ffffff',
            }}
          />

          <MapboxGL.CircleLayer
            id="clusteredPoints"
            filter={['>', 'point_count', 1]}
            maxZoomLevel={14}
            belowLayerID="pointCount"
            style={{
              circleColor: '#0000ff',
              circleRadius: [
                'interpolate',
                ['linear'],
                ['get', 'point_count'],
                0,
                10,
                mapState.biggestCluster || 1000,
                25,
              ],
              circleOpacity: 0.8,
            }}
          />

          <MapboxGL.CircleLayer
            id="symbolLocationSymbols"
            filter={['!', ['has', 'point_count']]}
            minZoomLevel={7}
            style={{
              circleColor: '#ff0000',
              circleRadius: 8,
              circleOpacity: 0.8,
            }}
          />
        </MapboxGL.ShapeSource>
      </MapboxMap>
    </Container>
  )
}
```

**Versions:**
 - Platform: Android
 - Emulator/ Simulator: yes
 - react-native-mapbox-gl Version 8.1.0-rc.5
 - React Native Version: 0.63.3

**Comment by ferdicus** [comment]
hey there, sorry to be that guy, however we're not supporting under `23`.

See https://github.com/react-native-mapbox-gl/maps#prerequisit

**Comment by aless10** [comment]
I'm so sorry, thanks for the response. Cheers.

**Comment by ferdicus** [comment]
> I'm so sorry, thanks for the response. Cheers.

No worries, stay safe 👋🏿
