### ISSUE TITLE
App crash when ProGuard is set to true

### ISSUE THREAD

**Issue by RobertSasak** [react-native-mapbox-gl/maps#1183]
## Describe the bug

I am trying to reduce size of Android app in release. Easiest is to enable ProGuard which will mingle and remove unused code. This can be done easily by enabling *enableProguardInReleaseBuilds* in android/app/build.gradle file. However when set true the app will crash.

## To Reproduce
```sh
git clone https://github.com/react-native-mapbox-gl/maps.git
cd maps/example
yarn
# set accesstoken file

# set version of gradle from 6.2 to 6.3 in gradle-wrapper.properties 
# to prevent Could not initialize class org.codehaus.groovy.runtime.InvokerHelper build errror
# distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip

react-native run-android --variant=release --verbose
```
Verity that app works by navigating to User Location > Set User Location Render Mode and switching to Native render mode. Yes indeed.

Enable ProGuard in *example/android/app/build.gradle* file by changing false to true.
```gradle
/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true
```
Build release version of example and run again it on device.
```sh
react-native run-android --variant=release --verbose
```
Build succeed. However example app crash when running and producing following log in logcat.
```
E/ReactNativeJS: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
```
<details>
  <summary>Full log</summary>
```
2021-01-16 14:43:36.926 6037-11548/? E/ReactNativeJS: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
    This error is located at:
        in RCTMGLNativeUserLocation
        in R
        in L
        in RCTMGLAndroidTextureMapView
        in RCTView
        in View
        in W
        in RCTView
        in View
        in D
        in B
        in c
        in y
        in P
        in RCTView
        in View
        in RCTView
        in View
        in RCTView
        in View
        in ForwardRef
        in RCTView
        in View
        in k
        in ForwardRef
        in PanGestureHandler
        in Unknown
        in RCTView
        in View
        in k
        in ForwardRef
        in RCTView
        in View
        in P
        in Unknown
        in RCTView
        in View
        in Unknown
        in RCTView
        in View
        in Unknown
        in T
        in b
        in RNCSafeAreaView
        in Unknown
        in Unknown
        in GestureHandlerRootView
        in Unknown
        in x
        in Unknown
        in Unknown
        in O
        in O
        in A
        in RCTView
        in View
        in RCTView
        in View
        in C
2021-01-16 14:43:36.930 6037-11548/? E/ReactNativeJS: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
    This error is located at:
        in O
        in A
        in RCTView
        in View
        in RCTView
        in View
        in C
2021-01-16 14:43:36.930 6037-11548/? E/ReactNativeJS: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
    This error is located at:
        in O
        in A
        in RCTView
        in View
        in RCTView
        in View
        in C
2021-01-16 14:43:36.937 6037-11549/? E/unknown:ReactNative: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
    This error is located at:
        in RCTMGLNativeUserLocation
        in R
        in L
        in RCTMGLAndroidTextureMapView
        in RCTView
        in View
        in W
        in RCTView
        in View
        in D
        in B
        in c
        in y
        in P
        in RCTView
        in View
        in RCTView
        in View
        in RCTView
        in View
        in ForwardRef
        in RCTView
        in View
        in k
        in ForwardRef
        in PanGestureHandler
        in Unknown
        in RCTView
        in View
        in k
        in ForwardRef
        in RCTView
        in View
        in P
        in Unknown
        in RCTView
        in View
        in Unknown
        in RCTView
        in View
        in Unknown
        in T
        in b
        in RNCSafeAreaView
        in Unknown
        in Unknown
        in GestureHandlerRootView
        in Unknown
        in x
        in Unknown
        in Unknown
        in O
        in O
        in A
        in RCTView
        in View
        in RCTView
        in View
        in C, stack:
    exports@9:286
    exports@184:1049
    get@179:875
    ai@92:54377
    Nl@92:74916
    Cl@92:74805
    Rl@92:74658
    Pl@92:74425
    Tl@92:71558
    Tl@-1
    <unknown>@92:23572
    unstable_runWithPriority@201:3882
    an@92:23519
    ln@92:23454
    xe@92:89263
    Se@92:12419
    Re@92:12808
    receiveTouches@92:13600
    value@27:3350
    <unknown>@27:747
    value@27:2610
    value@27:719
    value@-1
2021-01-16 14:43:36.939 6037-11549/? E/unknown:ReactNative: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
    This error is located at:
        in O
        in A
        in RCTView
        in View
        in RCTView
        in View
        in C, stack:
    exports@9:286
    exports@184:1049
    get@179:875
    ai@92:54377
    Nl@92:74916
    Cl@92:74805
    Rl@92:74658
    Pl@92:74425
    Tl@92:71558
    Tl@-1
    <unknown>@92:23572
    unstable_runWithPriority@201:3882
    an@92:23519
    ln@92:23454
    xe@92:89263
    Se@92:12419
    Re@92:12808
    receiveTouches@92:13600
    value@27:3350
    <unknown>@27:747
    value@27:2610
    value@27:719
    value@-1
2021-01-16 14:43:36.945 6037-11549/? E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.common.d: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
    This error is located at:
        in O
        in A
        in RCTView
        in View
        in RCTView
        in View
        in C, stack:
    exports@9:286
    exports@184:1049
    get@179:875
    ai@92:54377
    Nl@92:74916
    Cl@92:74805
    Rl@92:74658
    Pl@92:74425
    Tl@92:71558
    Tl@-1
    <unknown>@92:23572
    unstable_runWithPriority@201:3882
    an@92:23519
    ln@92:23454
    xe@92:89263
    Se@92:12419
    Re@92:12808
    receiveTouches@92:13600
    value@27:3350
    <unknown>@27:747
    value@27:2610
    value@27:719
    value@-1
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:134)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
        at android.os.Looper.loop(Looper.java:219)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
        at java.lang.Thread.run(Thread.java:929)
2021-01-16 14:43:36.945 6037-11549/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.common.d: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
    This error is located at:
        in O
        in A
        in RCTView
        in View
        in RCTView
        in View
        in C, stack:
    exports@9:286
    exports@184:1049
    get@179:875
    ai@92:54377
    Nl@92:74916
    Cl@92:74805
    Rl@92:74658
    Pl@92:74425
    Tl@92:71558
    Tl@-1
    <unknown>@92:23572
    unstable_runWithPriority@201:3882
    an@92:23519
    ln@92:23454
    xe@92:89263
    Se@92:12419
    Re@92:12808
    receiveTouches@92:13600
    value@27:3350
    <unknown>@27:747
    value@27:2610
    value@27:719
    value@-1
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:134)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
        at android.os.Looper.loop(Looper.java:219)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
        at java.lang.Thread.run(Thread.java:929)
2021-01-16 14:43:36.947 2558-2558/? E/HwLBSService.HwNLPDBManager: closedb 
2021-01-16 14:43:36.952 6037-11549/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.rnmapboxglexample, PID: 6037
    com.facebook.react.common.d: Invariant Violation: requireNativeComponent: "RCTMGLNativeUserLocation" was not found in the UIManager.
    This error is located at:
        in O
        in A
        in RCTView
        in View
        in RCTView
        in View
        in C, stack:
    exports@9:286
    exports@184:1049
    get@179:875
    ai@92:54377
    Nl@92:74916
    Cl@92:74805
    Rl@92:74658
    Pl@92:74425
    Tl@92:71558
    Tl@-1
    <unknown>@92:23572
    unstable_runWithPriority@201:3882
    an@92:23519
    ln@92:23454
    xe@92:89263
    Se@92:12419
    Re@92:12808
    receiveTouches@92:13600
    value@27:3350
    <unknown>@27:747
    value@27:2610
    value@27:719
    value@-1
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:134)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
        at android.os.Looper.loop(Looper.java:219)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
        at java.lang.Thread.run(Thread.java:929)
2021-01-16 14:43:36.955 2718-3302/? E/GnssDftUploadManager: interferenceWeakScale is null.
```
</details>
**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 9
 - Device: Huawei P20
 - Emulator/ Simulator: no
 - Dev OS: MacOS
 - react-native-mapbox-gl Version master 8.0.
 - React Native Version 0.63.0

## Solution

Similar issue was already fixed in https://github.com/react-native-mapbox-gl/maps/pull/260. As far I can see solution is fairly simple. Replace all the calls to *getSimpleName()* with just a string. So it cannot be mingled when ProGuard is enabled.

Replace

```java
 public static final String REACT_CLASS = RCTMGLCallout.class.getSimpleName();
```
with
```java
public static final String REACT_CLASS = "RCTMGLCallout";
```

You may be wondering why is this issue back. As it turns out I have created PR to upgrade example and at the same time turn off ProGuard be accident. https://github.com/react-native-mapbox-gl/maps/pull/432

**I am creating PR to fix this issue.**

**Comment by ferdicus** [comment]
PR is merged - closing
