### ISSUE TITLE
[Android] FillLayer fillPattern causing instant crash

### ISSUE THREAD

**Issue by amphithere** [react-native-mapbox-gl/maps#123]
**Describe the bug**
When trying to use the fillPattern style on FillLayer on Android 9 (haven't tried on iOS yet) it causes an instant crash. These are the logs that crashlytics have given me.
```
Fatal Exception: java.lang.ClassCastException: Value for value cannot be cast from ReadableNativeArray to String
       at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:150)
       at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:142)
       at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:192)
       at com.mapbox.rctmgl.components.styles.RCTMGLStyleValue.getString(RCTMGLStyleValue.java:81)
       at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory.setFillPattern(RCTMGLStyleFactory.java:837)
       at com.mapbox.rctmgl.components.styles.RCTMGLStyleFactory$1.onAllImagesLoaded(RCTMGLStyleFactory.java:76)
       at com.mapbox.rctmgl.utils.DownloadMapImageTask.onPostExecute(DownloadMapImageTask.java:88)
       at com.mapbox.rctmgl.utils.DownloadMapImageTask.onPostExecute(DownloadMapImageTask.java:23)
       at android.os.AsyncTask.finish(AsyncTask.java:695)
       at android.os.AsyncTask.access$600(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

When changing the style to fillColor, it works perfectly fine with the same filter.

Here is the code I am using and patternZips is an array of zipcodes represented as strings. GEOID10 is the property that matches the zipcode.

```
 <MapboxGL.FillLayer
            id="zipcode-boundaries-pattern"
            belowLayerID="zipcode-symbol"
            aboveLayerID="zipcode-boundaries"
            minZoomLevel={8}
            sourceLayerID="SuperZips-clhfv6"
            filter={['match', ['get', 'GEOID10'], patternZips, true, false]}
            style={{
              fillPattern: zipPattern,
            }}
          />
```
This is how I'm importing zipPattern:
```
import zipPattern from '../../../../assets/other-vector-stripe.png';
```

This used to work on the previous https://github.com/nitaliano/react-native-mapbox-gl version (minus expression syntax).

**To Reproduce**
Use fillPattern style on FillLayer.

**Expected behavior**
The polygon should be filled with the pattern imported.

**Versions:**
 - Platfrom: Android
 - Device: Pixel 3
 - OS: Android 9
 - SDK Version 28
 - React Native Version 0.59.5

**Comment by mfazekas** [comment]
@amphithere thanks,

the issue is here:
https://github.com/react-native-mapbox-gl/maps/blob/9e3310ae56ad6872437d3a82ee1e5f9fd2bedc90/scripts/autogenHelpers/globals.js#L188-L192

we should be checking prop.image not prop.name
