### ISSUE TITLE
[Android] Crash when opening a screen with map in Android 11

### ISSUE THREAD

**Issue by AndresAltomobile** [react-native-mapbox-gl/maps#1286]
**Describe the bug**  
Every time I open a screen that has a map, the application crashes. 
It seems this has to do with the latest version of Android. Android 11. 
This crash did not occur before the last update of the operating system.

**To Reproduce**  
Open a screen with a map.

**Expected behavior**  
The screen should show the content (map).

**Actual behavior**  
Crashes the app when we try to open a screen with a map.

**Screenshots** 
 ![Screen Shot 2021-03-19 at 2 13 38 PM](https://user-images.githubusercontent.com/50252292/111837338-5e773800-88bd-11eb-9575-f5214e972b20.png)

![Screenshot_20210319-140733_Vibemap](https://user-images.githubusercontent.com/50252292/111837138-05a79f80-88bd-11eb-8558-864382be46fd.jpg)

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 11
 - Device: Samsung Galaxy A51
 - Emulator/ Simulator: No
 - Dev OS: [e.g. OSX 11.0.1, Win10]
 - react-native-mapbox-gl Version 8.1.0
 - React Native Version: 0.63.4

**Additional context**  
Logs:

```
Fatal Exception: java.lang.SecurityException: getDataNetworkTypeForSubscriber: uid 10306 does not have android.permission.READ_PHONE_STATE.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3706)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3670)
       at com.mapbox.android.telemetry.m0.h(:10)
       at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(:21)
       at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(:25)
       at com.mapbox.mapboxsdk.maps.m.a(:8)
       at com.mapbox.rctmgl.components.mapview.c.<init>(:45)
       at com.mapbox.rctmgl.components.mapview.b.<init>()
       at com.mapbox.rctmgl.components.mapview.RCTMGLAndroidTextureMapViewManager.createViewInstance(:11)
       at com.mapbox.rctmgl.components.mapview.RCTMGLAndroidTextureMapViewManager.createViewInstance()
       at com.facebook.react.uimanager.ViewManager.createViewInstance()
       at com.facebook.react.uimanager.ViewManager.createView()
       at com.facebook.react.uimanager.m.a(:34)
       at com.facebook.react.uimanager.v0$e.execute(:23)
       at com.facebook.react.uimanager.v0$a.run(:114)
       at com.facebook.react.uimanager.v0.j(:53)
       at com.facebook.react.uimanager.v0.j()
       at com.facebook.react.uimanager.v0$j.b(:31)
       at com.facebook.react.uimanager.e.a()
       at com.facebook.react.modules.core.g$d.a(:46)
       at com.facebook.react.modules.core.a$a$a.doFrame(:2)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:740)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by skicson** [comment]
This[ issue has to do with a deprecated Android call](https://github.com/mapbox/mapbox-gl-native-android/issues/425).  It was fixed in mapbox several months ago but has not been updated in this library.  A workaround is to add this line:
`implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0'`
to the @react-native-mapbox-gl/maps/android/rctmgl/build.gradle file under the 
` implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0`
 line.

**Comment by ferdicus** [comment]
Additionally a more succinct [reply](https://github.com/mapbox/mapbox-gl-native-android/issues/557) by @tobrun:
>Please update to a newer version of the SDK:
>    9.4.0
>Or pull in telemetry v6.1.0

Let us know if that helped, will reopen when you encounter additional issues 🙇🏿

**Comment by ferdicus** [comment]
See [this](https://github.com/react-native-mapbox-gl/maps/blob/master/android/install.md#react-native--0600) for a solution to this problem

**Comment by siMs0n** [comment]
Hello @ferdicus. I'm using this package as a plugin in an Expo custom development client. It's a convenient way of adding this great package without having to eject to the bare workflow. This means that Expo handles all Android and iOS code and I can't access it. But this also means that I can't implement your suggested solution. Would you reconsider upgrading the android SDK or adding the telemetry library to avoid crashing? I assume more people will start using it as a plugin and encounter this issue.

**Comment by ferdicus** [comment]
aye, agreed - will add the dependency to be included by default

**Comment by JonasHiltl** [comment]
Hi, I'm still encountering this issue with an Expo custom development client. @siMs0n did you manage to get it to work?

**Comment by hsnGh67** [comment]
This issue remains yet

**Comment by ferdicus** [comment]
> This issue remains yet.

There wasn't a new release since the merge - feel free to test against `master`

**Comment by durgapt** [comment]
@ferdicus  I have tried the following commands to download master branch. Unfortunately, all of them were trying to download the latest version 8.3.0 and failed with the following error. Can you provide command for installing master branch?

npm install "git+https://github.com/react-native-mapbox-gl/maps.git#master" --save
npm install git@github.com:react-native-mapbox-gl/maps.git --save
npm install "git://github.com/react-native-mapbox-gl/maps.git#master" --save
npm install https://github.com/react-native-mapbox-gl/maps.git --save
npm install @react-native-mapbox-gl/maps#master --save

**Error:**
65242 info lifecycle @react-native-mapbox-gl/maps@8.3.0~prepare: Failed to exec prepare script
65243 verbose stack Error: @react-native-mapbox-gl/maps@8.3.0 prepare: `yarn build:plugin`
65243 verbose stack spawn ENOENT
65243 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
65243 verbose stack     at ChildProcess.emit (events.js:314:20)
65243 verbose stack     at maybeClose (internal/child_process.js:1047:16)
65243 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
65244 verbose pkgid @react-native-mapbox-gl/maps@8.3.0

**Comment by MendelBak** [comment]
I faced this issue when trying a new install. Adding ` <uses-permission android:name="android.permission.READ_PHONE_STATE"/>` to the `app/src/main/AndroidManifest.xml` file resolved this issue.

**Comment by ferdicus** [comment]
> I faced this issue when trying a new install. Adding ` <uses-permission android:name="android.permission.READ_PHONE_STATE"/>` to the `app/src/main/AndroidManifest.xml` file resolved this issue.

This is definitively _not_ required by this lib. 
Whatever issue you might've had, glad that it got resolved, however we do not require such permissions.  

All required permissions are noted in the install guide

**Comment by ferdicus** [comment]
having just written that, maybe the expo plugin isn't aware of versioning and only always gets the latest release 🤔 
Sorry, someone with more knowledge about `expo` can maybe explain how on can define versions of pulled in libs?

**Comment by MendelBak** [comment]
> Ok - so I literally had this issue every single time I ran on Android. Last night I changed my `app.json` to include READ_PHONE STATE:
> 
> ```
>     "android": {
>       "permissions": ["READ_PHONE_STATE"],
> ```
> 
> and everything magically sprang to life. Today as a sanity check I removed the permission and it still works fine... Not sure how I fell off the grid here, but I'm a happy camper now.

Yep. I did the same thing and it worked. I tried to add this to an FAQ in the docs but was told that it's impossible for this to have resolved my issue.

**Comment by Alifhossain2543** [comment]
Go to @react-native-mapbox-gl/maps under node_modules directory. Then go to android->rctmgl-> and open up build.gradle . Then implement this line under Mapbox SDK (customizableDependencies).         //implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0'

or replace full of it with 
    // Mapbox SDK
  customizableDependencies('rnmbglMapboxLibs') {
        implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.1.0'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0'
        implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0'
}
