### ISSUE TITLE
ANR after calling setTileCountLimit()

### ISSUE THREAD

**Issue by RobertSasak** [react-native-mapbox-gl/maps#1476]
**Describe the bug**  
Calling `setTileCountLimit(10000)` right after `setAccessToken(mapboxApiKey)`cause application to stop responding. 

Or sometimes I get following error in logcat or firebase crashlytics
```
Fatal Exception: com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException: 
Using MapView requires calling Mapbox.getInstance(Context context, String accessToken) before inflating or creating the view. The access token parameter is required when using a Mapbox service.
Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
       at com.mapbox.mapboxsdk.Mapbox.validateMapbox(Mapbox.java:203)
       at com.mapbox.mapboxsdk.Mapbox.getAccessToken(Mapbox.java:84)
       at com.mapbox.mapboxsdk.storage.FileSource.<init>(FileSource.java:369)
       at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:92)
       at com.mapbox.mapboxsdk.offline.OfflineManager.<init>(OfflineManager.java:134)
       at com.mapbox.mapboxsdk.offline.OfflineManager.getInstance(OfflineManager.java:154)
       at com.mapbox.rctmgl.modules.RCTMGLOfflineModule.setTileCountLimit(RCTMGLOfflineModule.java:417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:213)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:929)
```

**To Reproduce**  

I managed to reproduce this error in production as well on my own device when debugging. 

Example:
```js
import React from 'react'
import { AppRegistry } from 'react-native'
import MapboxGL from '@react-native-mapbox-gl/maps'

console.error('Before')
MapboxGL.setAccessToken('mapboxApiKey')
console.error('Middle')
// setTimeout(() => { // <- workaround to make it work
MapboxGL.offlineManager.setTileCountLimit(10000)
// }, 0)
console.error('After')

const App = () => <MapboxGL.MapView style={{ flex: 1 }} />

AppRegistry.registerComponent('app', () => App)

export default App
```

**Expected behavior**  
It would be nice if we can enforce order of execution of `setAccessToken()` and `setTileCountLimit()`. This is not really a big bug. There is a simple workaround with `setTimeout()`. 

My biggest consern is that Mapbox library might start to delete already cached tiles. 

**Actual behavior**  
There seems to be a race condition. I guess calls over react bridge can change order or take sometimes longer. This cause that `setTileCountLimit()` is invoked before valid _accessToken_ is set. 

**Versions:**  
 - Platform: Android (iOS works)
 - Platform OS: Android 10
 - Device: Samsung SM-G935F
 - Emulator/ Simulator: no
 - Dev OS: macOS 11.5
 - react-native-mapbox-gl Version 8.2.0-beta2
 - Mapbox GL version default
 - React Native Version 0.63.4

**Comment by ferdicus** [comment]
Hi @RobertSasak, 
I looked a bit into this.

When comparing the two calls (which we're not handling in an in-between JS layer), `setAccessToken` seems to be more asyncy than `setTileCountLimit`.

`setAccessToken`:
https://github.com/react-native-mapbox-gl/maps/blob/f38ff0b17eca01255e87b6c229fd42f5a5d26e20/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java#L287-L295




in comparison `setTileCountLimit`:
https://github.com/react-native-mapbox-gl/maps/blob/f38ff0b17eca01255e87b6c229fd42f5a5d26e20/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java#L415-L419


I guess you could add a check into `setTileCountLimit` to ensure, that `accessToken` is set before executing it, but then again, this could happen with many other methods as well... I tried setting the accessToken in sync, without luck (on an aside: react-native native module docs are ... underwhelming....).

I would simply recommend to set your accesstoken as soon as possible on app start (`index.js`/ `app.js`) and by the time you render your other views it should hopefully be done.

sorry for not having a more fruitful answer

**Comment by RobertSasak** [comment]
Thank you for your investigation. As there is no real solution and there is a clear workaround I am closing this issue.
