### ISSUE TITLE
Crash when getCenter() is called

### ISSUE THREAD

**Issue by badredaha** [react-native-mapbox-gl/maps#1498]
**Describe the bug**  
Randomly the App Crash when we call getCenter() method.

**To Reproduce**  
Steps to reproduce the behavior. 

Please include a single standalone React Native component.  
Use [our BugReportTemplate](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/BugReportTemplate.js) screens as a starting point.
Please simplify the example as much as possible!

Chances that a bug report will be investiagete and worked on are exponetially higher with a complete and _working_ repro BugTemplate!

Code RN:
```
const centerCoordinate = await this._map.getCenter();
      if (centerCoordinate.length > 0) {
        const longitude = centerCoordinate[0];
        const latitude = centerCoordinate[1];
  
        this.newSearch({
          longitude: longitude,
          latitude: latitude,
        });
      }
```
**Crash stack:**
`Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException
Error while updating property 'stop' of a view managed by: RCTMGLCamera
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp
Caused by java.lang.reflect.InvocationTargetException
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:87)
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:136)
com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:56)
com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:49)
com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties (NativeViewHierarchyManager.java:137)
com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute (UIViewOperationQueue.java:94)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:917)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1028)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:48)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1088)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:964)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)
Caused by com.google.gson.JsonSyntaxException
java.lang.IllegalStateException: Expected NUMBER but was NULL at path $.coordinates[0]
com.google.gson.Gson.fromJson (Gson.java:944)
com.google.gson.Gson.fromJson (Gson.java:817)
com.mapbox.geojson.Feature.fromJson (Feature.java:82)
com.mapbox.rctmgl.utils.GeoJSONUtils.toPointGeometry (GeoJSONUtils.java:155)
com.mapbox.rctmgl.components.camera.CameraStop.fromReadableMap (CameraStop.java:135)
com.mapbox.rctmgl.components.camera.RCTMGLCameraManager.setStop (RCTMGLCameraManager.java:43)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp (ViewManagersPropertyCache.java:87)
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java:136)
com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps (ViewManagerPropertyUpdater.java:56)
com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java:49)
com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties (NativeViewHierarchyManager.java:137)
com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute (UIViewOperationQueue.java:94)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:917)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1028)
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 (UIViewOperationQueue.java:48)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java:1088)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java:29)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java:175)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java:85)`

**Versions (please complete the following information):**  
 - Platform OS: Android 8,9,10,11
 - react-native-mapbox-gl Version 8.2.0
 - Mapbox GL version 8.2.1
 - React Native Version 0.64.2

**Comment by ferdicus** [comment]
Not sure what's happening here, can you try to reproduce this within the `example` app please. 
I've used the `FlyTo` example and used this code to request the info:
```js
setInterval(async () => {
  if (!this.map) return;
  const center = await this.map.getCenter();
  console.log('------', center);
}, 100)
```

was rapid firing the current `center` into the terminal without an issue 🤷🏿

**Comment by badredaha** [comment]
Thank you I will try this in production and I will give you feedback.

**Comment by badredaha** [comment]
I just tested the code snippet and the result is the same ! 

2021-08-23 15:35:37.436 19832-19832/? E/unknown:ViewManager: Error while updating prop stop
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.a1$l.e(ViewManagersPropertyCache.java:4)
        at com.facebook.react.uimanager.y0$c.b(ViewManagerPropertyUpdater.java:2)
        at com.facebook.react.uimanager.y0.g(ViewManagerPropertyUpdater.java:5)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3)
        at com.facebook.react.uimanager.m.E(NativeViewHierarchyManager.java:4)
        at com.facebook.react.uimanager.u0$w.execute(UIViewOperationQueue.java:1)
        at com.facebook.react.uimanager.u0$a.run(UIViewOperationQueue.java:18)
        at com.facebook.react.uimanager.u0.U(UIViewOperationQueue.java:10)
        at com.facebook.react.uimanager.u0.s(UIViewOperationQueue.java:1)
        at com.facebook.react.uimanager.u0$j.c(UIViewOperationQueue.java:6)
        at com.facebook.react.uimanager.f.a(GuardedFrameCallback.java:1)
        at com.facebook.react.modules.core.g$d.a(ReactChoreographer.java:7)
        at com.facebook.react.modules.core.a$a$a.doFrame(ChoreographerCompat.java:1)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected NUMBER but was NULL at path $.coordinates[0]
        at com.google.gson.f.i(Gson.java:12)
        at com.google.gson.f.k(Gson.java:2)
        at com.google.gson.f.m(Gson.java:2)
        at com.google.gson.f.l(Gson.java:1)
        at com.mapbox.geojson.Feature.fromJson(Feature.java:4)
        at com.mapbox.rctmgl.utils.e.s(GeoJSONUtils.java:1)
        at com.mapbox.rctmgl.components.camera.a.b(CameraStop.java:7)
        at com.mapbox.rctmgl.components.camera.RCTMGLCameraManager.setStop(RCTMGLCameraManager.java:1)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.a1$l.e(ViewManagersPropertyCache.java:4) 
        at com.facebook.react.uimanager.y0$c.b(ViewManagerPropertyUpdater.java:2) 
        at com.facebook.react.uimanager.y0.g(ViewManagerPropertyUpdater.java:5) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:3) 
        at com.facebook.react.uimanager.m.E(NativeViewHierarchyManager.java:4) 
        at com.facebook.react.uimanager.u0$w.execute(UIViewOperationQueue.java:1) 
        at com.facebook.react.uimanager.u0$a.run(UIViewOperationQueue.java:18) 
        at com.facebook.react.uimanager.u0.U(UIViewOperationQueue.java:10) 
        at com.facebook.react.uimanager.u0.s(UIViewOperationQueue.java:1) 
        at com.facebook.react.uimanager.u0$j.c(UIViewOperationQueue.java:6) 
        at com.facebook.react.uimanager.f.a(GuardedFrameCallback.java:1) 
        at com.facebook.react.modules.core.g$d.a(ReactChoreographer.java:7) 
        at com.facebook.react.modules.core.a$a$a.doFrame(ChoreographerCompat.java:1) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:723) 
        at android.view.Choreographer.doFrame(Choreographer.java:655) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.IllegalStateException: Expected NUMBER but was NULL at path $.coordinates[0]
        at com.google.gson.internal.bind.e.H0(JsonTreeReader.java:4)
        at com.mapbox.geojson.BaseCoordinatesTypeAdapter.readPointList(BaseCoordinatesTypeAdapter.java:5)
        at com.mapbox.geojson.ListOfDoublesCoordinatesTypeAdapter.read(ListOfDoublesCoordinatesTypeAdapter.java:2)
        at com.mapbox.geojson.ListOfDoublesCoordinatesTypeAdapter.read(ListOfDoublesCoordinatesTypeAdapter.java:1)
        at com.mapbox.geojson.BaseGeometryTypeAdapter.readCoordinateContainer(BaseGeometryTypeAdapter.java:11)
        at com.mapbox.geojson.Point$GsonTypeAdapter.read(Point.java:2)
        at com.mapbox.geojson.Point$GsonTypeAdapter.read(Point.java:1)
        at com.google.gson.o.fromJsonTree(TypeAdapter.java:2)
        at com.google.gson.typeadapters.RuntimeTypeAdapterFactory$a.read(RuntimeTypeAdapterFactory.java:7)
        at com.google.gson.o$a.read(TypeAdapter.java:3)
        at com.mapbox.geojson.Feature$GsonTypeAdapter.read(Feature.java:14)
        at com.mapbox.geojson.Feature$GsonTypeAdapter.read(Feature.java:1)
        at com.google.gson.f.i(Gson.java:6)
