### ISSUE TITLE
[Android] java.lang.IllegalArgumentException: Null duration passed into easeCamera

### ISSUE THREAD

**Issue by winseyli** [react-native-mapbox-gl/maps#291]
**Describe the bug**
No crash on iOS but the app crashes once the map initialise on the screen on Android.

**To Reproduce**
Not required.

**Expected behavior**
No crash..

**Android Logcat**
```2019-08-01 22:17:34.789 29119-29119/xx.xx.reactnative.staging E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nz.co.homes.reactnative.staging, PID: 29119
    java.lang.IllegalArgumentException: Null duration passed into easeCamera
        at com.mapbox.mapboxsdk.maps.MapboxMap.easeCamera(MapboxMap.java:527)
        at com.mapbox.mapboxsdk.maps.MapboxMap.easeCamera(MapboxMap.java:484)
        at com.mapbox.rctmgl.components.camera.CameraUpdateItem.run(CameraUpdateItem.java:69)
        at com.mapbox.rctmgl.components.camera.CameraUpdateQueue.execute(CameraUpdateQueue.java:68)
        at com.mapbox.rctmgl.components.camera.RCTMGLCamera.updateCamera(RCTMGLCamera.java:189)
        at com.mapbox.rctmgl.components.camera.RCTMGLCamera.addToMap(RCTMGLCamera.java:139)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onMapReady(RCTMGLMapView.java:415)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1191)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1177)
        at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:207)
        at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:61)
        at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:321)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6585)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: ASUS Zenfone 4
 - OS: Android 8.0.0
 - SDK Version 28
 - React Native Version 0.59.9

**Comment by winseyli** [comment]
seems like it is related to https://github.com/react-native-mapbox-gl/maps/issues/254
It doesn't crash if I commented out the <MapboxGL.Camera>.
I use <MapboxGL.ShapeSource> at the same time within the same <MapboxGL.MapView>.

**Comment by mfazekas** [comment]
Yep, the default `animationMode` easeTo does not support 0 as animation duration.
Either use non zero a duration, or use `defaultSettings` properties to setup the initial camera

**Comment by winseyli** [comment]
I think this is a bug and it's "good first issue" so it shouldn't be 'wontfix".

**Comment by kristfal** [comment]
And our dear bot stale obeys ;) happy to accept PRs for this.
