### ISSUE TITLE
HttpRequestUtil.setOkHttpClient results in a crash on Android 

### ISSUE THREAD

**Issue by geohacker** [react-native-mapbox-gl/maps#293]
👋 thank you for maintaining and developing react-native-mapbox-gl. We've been using rctmgl for an app call [Observe](https://github.com/developmentseed/observe) - an offline POI editor for OpenStreetMap. 
 
**Describe the bug**
We're in the process of upgrading the rctmgl version and have run into the following issue. 
```
07-30 11:01:02.627 20892-20892/com.developmentseed.observe E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.developmentseed.observe, PID: 20892
    java.lang.ExceptionInInitializerError
        at com.mapbox.mapboxsdk.module.http.HttpRequestImpl.setOkHttpClient(HttpRequestImpl.java:103)
        at com.mapbox.mapboxsdk.module.http.HttpRequestUtil.setOkHttpClient(HttpRequestUtil.java:50)
        at com.developmentseed.observe.MainActivity.onCreate(MainActivity.java:95)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException: 
    Using MapView requires calling Mapbox.getInstance(Context context, String accessToken) before inflating or creating the view. The access token parameter is required when using a Mapbox service.
    Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
    More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
        at com.mapbox.mapboxsdk.Mapbox.validateMapbox(Mapbox.java:178)
        at com.mapbox.mapboxsdk.Mapbox.getApplicationContext(Mapbox.java:110)
        at com.mapbox.mapboxsdk.http.HttpIdentifier.getIdentifier(HttpIdentifier.java:21)
        at com.mapbox.mapboxsdk.module.http.HttpRequestImpl.<clinit>(HttpRequestImpl.java:39)
```

This looks like it's crashing because of overriding the http client like here https://github.com/developmentseed/observe/blob/cc682e840abda9ea240698d709454c6d710ccd92/android/app/src/main/java/com/developmentseed/observe/MainActivity.java#L95

**To Reproduce**
I was able to reproduce this issue with the example in this repository. The example code with the change to override the httpclient is here https://github.com/geohacker/rctmgl-example. The change is here https://github.com/geohacker/rctmgl-example/blob/master/android/app/src/main/java/com/rnmapboxglexample/MainApplication.java#L55-L59

You can clone, and run the example by [following the instructions](https://github.com/geohacker/rctmgl-example/blob/master/README.md)

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Pixel via Emulator
 - SDK Version 28
 - React Native Version 0.59

**Additional context**
I came across a ticket in mapboxgl-native that is referring to a similar error https://github.com/mapbox/mapbox-gl-native/issues/13253

cc @mfazekas @nitaliano @kristfal

**Comment by mfazekas** [comment]
@geohacker my understandig of the error, it seems you need to set AccessToken before calling any mapbox functions. 

I'm closing as i don't think this is related to rnmpgl.

**Comment by geohacker** [comment]
@mfazekas thank you for the quick response. I'm not sure exactly what we're doing incorrectly. When I comment out the http client overriding, everything seem work well. So is there another step to set the accessToken when we override the client? 

I'm pretty new to all this, so pardon my question!

**Comment by kylebarron** [comment]
I get the same error, when I don't set the access token, but I'm using self-hosted maps, so I shouldn't have to pass an access token when the styleURL isn't pointing to Mapbox. It works fine on iOS when the access token isn't set.

**Comment by bboure** [comment]
@mfazekas  Like @kylebarron I am not using Mapbox but another provider, and I am getting the same error.
I should not need to provide a Mapbox API key.
on IOS it works fine.

For now a workaround is to call
```js
MapboxGL.setAccessToken('fake_key');
```

HOwever, this causes an request to mapbox with a 401 error.
The rest works fine.

**Comment by mfazekas** [comment]
@bboure can you try `MapboxGL.setAccessToken(null)` that should work with no req to mapbox

**Comment by bboure** [comment]
@mfazekas thanks for you help. Using null seems to work. 

However, it gives a [TS error](https://github.com/react-native-mapbox-gl/maps/blob/master/index.d.ts#L114) because the accessToken is not nullable. 

````ts
MapboxGL.setAccessToken('');
````
works too.

It might be useful to put that somewhere in the doc.

On a side note, the reason because `setAccessToken` is required on Android, is because otherwise [getInstance()](https://github.com/react-native-mapbox-gl/maps/blob/a60ae1509b6c3f7f417476ac066fc64f4d6920fe/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java#L292) never gets called
