### ISSUE TITLE
[Android] MapboxGL.Camera with followUserLocation throws an exception

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#75]
**Describe the bug**
Currently in the process of kicking the tires of 7.0.0 I've noticed the following behavior:
Using `MapboxGL.Camera` with prop `followUserLocation` throws an exception:

```java
Error while updating prop 'followUserLocation' of a view managed by: RCTMGLCamera
```

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
```

callStack info:
```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
        at com.mapbox.rctmgl.location.UserTrackingMode.fromString(UserTrackingMode.java:67)
        at com.mapbox.rctmgl.components.camera.RCTMGLCamera.updatedFollowUserMode(RCTMGLCamera.java:495)
        at com.mapbox.rctmgl.components.camera.RCTMGLCamera.setFollowUserLocation(RCTMGLCamera.java:485)
        at com.mapbox.rctmgl.components.camera.RCTMGLCameraManager.setFollowUserLocation(RCTMGLCameraManager.java:59)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:132) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:51) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:265) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1109) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1080) 
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:166) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:977) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:791) 
        at android.view.Choreographer.doFrame(Choreographer.java:723) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6661)
```

**To Reproduce**
This is the code I used:
```js
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";

import MapboxGL from "@react-native-mapbox-gl/maps";
MapboxGL.setAccessToken("<TOKEN>");

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  container: {
    height: 300,
    width: 300,
    backgroundColor: "tomato"
  },
  map: {
    flex: 1
  }
});

export default class App extends Component {
  state = {
    permissonGranted: null
  };

  async componentDidMount() {
    const permissonGranted = await MapboxGL.requestAndroidLocationPermissions();
    this.setState({ permissonGranted });
  }

  render() {
    if (!this.state.permissonGranted) return null;
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map}>
            <MapboxGL.UserLocation visible={true} />
            <MapboxGL.Camera followUserLocation followUserMode="normal" />
          </MapboxGL.MapView>
        </View>
      </View>
    );
  }
}
```

*Notice:* the culprit seems to be a missing string that should've been passed to 
`UserTrackingMode.fromString` in UserTrackingMode.java ? When checked `value` is always `null` no matter the defined `followUserMode`

**Expected behavior**
User position is shown and Camera is following user position in the followUserMode specified.

**Screenshots**
![image](https://user-images.githubusercontent.com/26439946/58718040-e92b3200-83cc-11e9-97ff-c38f4396b247.png)

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: LG Q7
 - OS: OSX
 - SDK Version Android 8
 - React Native Version: 0.59.8

**Comment by ferdicus** [comment]
hey @mfazekas, thanks for taking care of this.
Can you elaborate a bit please on how the value can be `null` at that [line](https://github.com/mfazekas/maps-1/blob/e6f7a0992f8397c9fbde6431ed5cbb7347f29227/android/rctmgl/src/main/java/com/mapbox/rctmgl/location/UserTrackingMode.java#L65) when `followUserMode` was defined? 
Just curious.

**Comment by mfazekas** [comment]
@ferdicus i think `updatedFollowUserMode` also get's called from `setFollowUserLocation` .

We happen to have `this.refs.camera.setNativeProps({followUserLocation: true})` before the mode so we set followUserLocation first and it's possibl that followUserMode was not yet set on the native side and it defaults to null.

**Comment by ferdicus** [comment]
I see, thanks for taking the time explaining it. 👍

**Comment by Blind12** [comment]
Hi, 

I tried many times in many ways to use <MapboxGL.Camera followUserLocation/> with and without the prop followUserMode="normal". 

Every time, I got the error above with a null object ref. Is the doc not up to date or the examples I found in the doc using this prop?

Thank you for your time.

**Comment by anttijva** [comment]
To me it seems at the followUserMode is working a little weird. The icon doesn't change between modes, and the old userTrackingMode "followWithHeading" doesn't seem to exist anymore. 

I tried out multiple different configurations but can't seem to get it working.

**Comment by mfazekas** [comment]
@anttijva followUserMode now can be ['normal', 'compass', 'course'], `compass` is equivalent to old `followWithHeading`.
The icons could be changed via UserLocation#renderMode, but for now only `['normal','custom']` is supported.

**Comment by Blind12** [comment]
@mfazekas

Do you know if it's an expected behavior what you explained above ? About the followUserMode set to null by default and used by followUserMode. The workaround I found for now is to set a timer and set the followUserLocation : true when the component is mounted or after x seconds. 

Thank you.

**Comment by mfazekas** [comment]
@Blind12  doesn't sound good, you should be able to set both `followUserMode` and `followUserLocation` same time without timer

**Comment by Blind12** [comment]
"@react-native-mapbox-gl/maps": "^7.0.0-rc3",
"react-native": "0.59.9",
"react": "16.8.3",

This simple code : 

 ```
        <MapboxGL.MapView
            ref={(ref) => (this._map = ref)}
            style={{flex: 1}}
            animated={true}
            rotateEnabled={false}
            pitchEnabled={false}
          >

          <MapboxGL.UserLocation
            renderMode="normal"
          />
          <MapboxGL.Camera
            followUserLocation={true}
            followUserMode="normal"
          />

```
throw the error posted by the author.

**Comment by anttijva** [comment]
> @anttijva followUserMode now can be ['normal', 'compass', 'course'], `compass` is equivalent to old `followWithHeading`.
> The icons could be changed via UserLocation#renderMode, but for now only `['normal','custom']` is supported.

@mfazekas Okay that explains the icons, but the functionality is still a mystery. Before, if I activated followWithHeading/followWithCourse, the map would change position according to how I was turning the phone (using gyro/compass?) but now I can't seem to get that working. Any ideas?

**Comment by ShepelE** [comment]
Hi!
@ferdicus, It looks like the bug I had.
I found some workaround here: https://github.com/react-native-mapbox-gl/maps/issues/344
Please check if it helps in your case

**Comment by sugaith** [comment]
Still happening

**Comment by dorthwein** [comment]
still happening
