### ISSUE TITLE
8.0.0-rc2 doesn't pass google firebase test

### ISSUE THREAD

**Issue by vovka-s** [react-native-mapbox-gl/maps#792]
Hi, guys!
I tried to upload my app to google play store.
But I faced a problem: one of tests doesn't pass
![Screenshot from 2020-04-07 12-50-21](https://user-images.githubusercontent.com/9987233/78655339-8cdb4d80-78ce-11ea-8166-bfc3e7dd217f.png)
```
 FATAL EXCEPTION: main
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.m.a(com.mapbox.mapboxsdk.maps.z$c)' on a null object reference
	at com.mapbox.rctmgl.components.images.RCTMGLImages.c(RCTMGLImages.java:9)
	at com.mapbox.rctmgl.components.images.RCTMGLImages.access$100(RCTMGLImages.java:0)
	at com.mapbox.rctmgl.components.images.RCTMGLImages.access$500(RCTMGLImages.java:0)
	at com.mapbox.rctmgl.components.images.RCTMGLImages.addRemoteImages(RCTMGLImages.java:0)
	at com.mapbox.rctmgl.components.images.RCTMGLImages.hasNativeImages(RCTMGLImages.java:0)
	at com.mapbox.rctmgl.components.images.RCTMGLImages.removeFromMap(RCTMGLImages.java:0)
	at com.mapbox.rctmgl.components.images.RCTMGLImages.sendImageMissingEvent(RCTMGLImages.java:0)
	at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.b(RCTMGLMapView.java:70)
	at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.removeViewAt(RCTMGLMapViewManager.java:0)
	at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.removeViewAt(RCTMGLMapViewManager.java:2)
	at com.facebook.react.uimanager.ViewGroupManager.removeAllViews(ViewGroupManager.java:8)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:121)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:115)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:115)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.a(NativeViewHierarchyManager.java:307)
	at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:16)
	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:72)
	at com.facebook.react.uimanager.UIViewOperationQueue.i(UIViewOperationQueue.java:53)
	at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:0)
	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:0)
	at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:2)
	at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:0)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
```
![Screenshot from 2020-04-07 12-49-46](https://user-images.githubusercontent.com/9987233/78655349-906ed480-78ce-11ea-8fd8-6c4e8b0b4c84.png)

This seems to happen when the map removes markers
May be it is caused by not released version. 
Unfortunately, I can't get you not minimized stack trace.
Any ideas? 

 - Platform: Android
 - Device: Mi9 SE
 - Emulator/ Simulator: no
 - OS: android 10
 - react-native-mapbox-gl Version 8.0.0-rc2
 - React Native Version 0.61.5

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "17.+"
        firebaseVersion = "20.0.0"
        mediaCompatVersion = '1.0.1'
        supportV4Version = '1.0.0'
    }
```

**Comment by mfazekas** [comment]
You need to find the proguard files in your build. `/build/outputs/mapping/release/`?? 
mapping.txt might help you decode what is `com.mapbox.rctmgl.components.images.RCTMGLImages.c` and what is `com.mapbox.mapboxsdk.maps.m.a`

**Comment by vovka-s** [comment]
That's what I found:
`com.mapbox.rctmgl.components.images.RCTMGLImagesManager mManager -> c`
`com.mapbox.mapboxsdk.maps.MapView$FocalPointInvalidator focalInvalidator -> m`
`com.mapbox.mapboxsdk.maps.Projection getProjection() -> m`
`com.mapbox.mapboxsdk.maps.MapboxMapOptions textureMode(boolean) -> m`

Whole file: [mapping.txt](https://github.com/react-native-mapbox-gl/maps/files/4446345/mapping.txt)

**Comment by mfazekas** [comment]
From mapping:
```
 com.mapbox.mapboxsdk.maps.Style$OnStyleLoaded -> com.mapbox.mapboxsdk.maps.z$c:
```

So this 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.maps.m.a(com.mapbox.mapboxsdk.maps.z$c)' on a null object reference
``` 

is more than likely:

https://github.com/react-native-mapbox-gl/maps/blob/3bdcc9096eae981a5cc9911f03e8c42a42fa991b/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/images/RCTMGLImages.java#L69

The getMapboxMap() returns `null`.

**Comment by vovka-s** [comment]
Thanks!
