### ISSUE TITLE
React Native 61.5 + Android Emulator 9.0 (Pie) App crashes on load

### ISSUE THREAD

**Issue by GGrassiant** [react-native-mapbox-gl/maps#815]
**Issue I am facing**
When working with React Native 61.5 and Android Studio if the app includes react-native-mapbox-gl, the emulator will crash on load but only for Android 9.
Running the build on iOS simulator and Android emulator 8.0 and 10.0 is not crashing. It also works on a physical device (Samsung) with Android 7.

If I switch branches, to another one with no mapbox, it works fine on all OS's.

**Steps to reproduce**
1) Setup and create a view with a map
```

export default class Map extends Component {
  constructor(props) {
    super(props);
    this.state = {
      bounds: {
        ne: [-73.65529613380814, 45.54492921060108],
        sw: [-73.65685467142485, 45.544224880781854],
      },
      currentZoom: 18,
      selectedGeoJSON: null,
      currentArea: {
        id: null,
        level: null,
        name: '',
        coordinates: [0, 0],
      },
    };

    this.onSliderChange = this.onSliderChange.bind(this);
    this.onPressHandler = this.onPressHandler.bind(this);
  }

  onSliderChange(value) {
    this.setState({ currentZoom: value });
  }

  async onPressHandler(event) {
    const { screenPointX, screenPointY } = event.properties;
    const coordinates = await this.map.getCoordinateFromView([
      screenPointX,
      screenPointY,
    ]);

    const featureCollection = await this.map.queryRenderedFeaturesAtPoint(
      [screenPointX, screenPointY],
      ['!=', 'background', 'true'],
      ['building3d'],
    );

    const { features } = featureCollection;
    if (features.length) {
      const {
        id,
        properties: { level, name },
      } = features[0];

      this.setState({
        selectedGeoJSON: featureCollection,
        currentArea: {
          id,
          level,
          name,
          coordinates,
        },
      });
    }
  }

  componentDidMount() {
    MapboxGL.setTelemetryEnabled(false);
  }

  render() {
    return (
      <View style={styles.page}>
        <MapboxGL.MapView
          ref={(ref) => (this.map = ref)}
          style={styles.map}
          styleURL={
            'mapbox://styles/ergodim/ck8rxxtpm1n5s1io43ypvs2wi?fresh=true'
          }
          localizeLabels
          logoEnabled={false}
          compassEnabled={false}
          pitchEnabled={false}
          onPress={(event) => this.onPressHandler(event)}
        >
          <MapboxGL.Camera
            zoomLevel={this.state.currentZoom}
            minZoomLevel={this.state.currentZoom}
            maxZoomLevel={19}
            bounds={this.state.bounds}
            maxBounds={this.state.bounds}
          />

          <MapboxGL.Light style={{ position: [5, 90, -80] }} />

          <MapboxGL.ShapeSource id="indoorBuildingSource" shape={ergoMap}>
            <MapboxGL.FillExtrusionLayer
              id="building3d"
              style={layerStyles.building}
            />
          </MapboxGL.ShapeSource>

          {this.state.currentArea.id ? (
            <MapboxGL.ShapeSource
              id="selectedindoorBuildingSource"
              shape={this.state.selectedGeoJSON}
            >
              <MapboxGL.FillExtrusionLayer
                id="indoorBuildingSourceFill"
                style={layerStyles.selectedBuilding}
              />
            </MapboxGL.ShapeSource>
          ) : null}
        </MapboxGL.MapView>
        <Bubble>
          <>
            <Text>
              <Text style={layerStyles.selectedBuildingInfo}>
                Selected Zone
              </Text>
              : {this.state.currentArea.name}
              {'\n'}
              <Text style={layerStyles.selectedBuildingInfo}>Level</Text>:{' '}
              {this.state.currentArea.level}
              {'\n'}
              <Text style={layerStyles.selectedBuildingInfo}>Id</Text>:{' '}
              {this.state.currentArea.id}
              {'\n'}
              <Text style={layerStyles.selectedBuildingInfo}>
                Coordinates are
              </Text>
              {'\n'}
              <Text style={layerStyles.selectedBuildingInfo}>long</Text>:{' '}
              {this.state.currentArea.coordinates[0]}
              {'\n'}
              <Text style={layerStyles.selectedBuildingInfo}>lat</Text>:{' '}
              {this.state.currentArea.coordinates[1]}
            </Text>
            <View style={layerStyles.selectedBuildingButton}>
              <Bouton
                disabled={!this.state.selectedGeoJSON}
                color="blue"
                onPress={() =>
                  triggerModal('modal', 'info', {
                    titleAction: reservationMessages.confirmed,
                    name: this.state.currentArea.name,
                    dateFrom: new Date().toISOString(),
                    dateTo: new Date().toISOString(),
                    onManageReservation: () => console.log('booked'),
                  })
                }
              >
                Book now
              </Bouton>
            </View>
          </>
        </Bubble>

        <View style={styles.slider}>
          <Slider
            value={this.state.currentZoom}
            onValueChange={this.onSliderChange}
            thumbTintColor={variables.colorInfo}
            minimumValue={18}
            maximumValue={19}
            thumbTouchSize={{ width: 44, height: 44 }}
            maximumTrackTintColor={variables.colorSuccess}
            minimumTrackTintColor={variables.colorCharcoal}
          />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  page: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  slider: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    maxHeight: 60,
    paddingHorizontal: 24,
  },
});

const layerStyles = {
  building: {
    fillExtrusionOpacity: 1,
    fillExtrusionColor: ['get', 'color'],
  },
  selectedBuilding: {
    fillExtrusionOpacity: 0.5,
    fillExtrusionColor: 'yellow',
  },
  selectedBuildingInfo: {
    fontWeight: 'bold',
  },
  selectedBuildingButton: {
    marginTop: 10,
    alignSelf: 'stretch',
  },
};
```

2) Make sure the AVD you are using is running on Android 9.0

3) Launch the simulator with `react-native run-android`

**Logs**

When running  `adb logcat | grep react` for the failing version I get:

```
04-10 12:45:58.153  8083  8083 W System.err:    at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:290)
04-10 12:45:58.154  8083  8083 W System.err:    at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:265)
04-10 12:45:58.154  8083  8083 W System.err:    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:86)
04-10 12:45:58.154  8083  8083 W System.err:    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:38)
04-10 12:45:58.154  8083  8083 W System.err:    at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:103)
04-10 12:45:58.154  8083  8083 W System.err:    at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
04-10 12:45:58.154  8083  8083 W System.err:    at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:83)
04-10 12:45:58.154  8083  8083 W System.err:    at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
04-10 12:45:58.158  8083  8083 W System.err:    at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:290)
04-10 12:45:58.159  8083  8083 W System.err:    at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:265)
04-10 12:45:58.159  8083  8083 W System.err:    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:86)
04-10 12:45:58.159  8083  8083 W System.err:    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:38)
04-10 12:45:58.159  8083  8083 W System.err:    at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:103)
04-10 12:45:58.159  8083  8083 W System.err:    at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
04-10 12:45:58.159  8083  8083 W System.err:    at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:83)
04-10 12:45:58.159  8083  8083 W System.err:    at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
04-10 12:45:58.166  8083  8083 W System.err:    at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:290)
04-10 12:45:58.166  8083  8083 W System.err:    at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:265)
04-10 12:45:58.166  8083  8083 W System.err:    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:86)
04-10 12:45:58.166  8083  8083 W System.err:    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:38)
04-10 12:45:58.166  8083  8083 W System.err:    at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:103)
04-10 12:45:58.166  8083  8083 W System.err:    at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:88)
04-10 12:45:58.167  8083  8083 W System.err:    at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:83)
04-10 12:45:58.167  8083  8083 W System.err:    at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
04-10 12:45:58.647  8083  8128 E AndroidRuntime: FATAL EXCEPTION: create_react_context
04-10 12:45:58.647  8083  8128 E AndroidRuntime:        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
04-10 12:45:58.647  8083  8128 E AndroidRuntime:        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
04-10 12:45:58.647  8083  8128 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:952)
```

**Steps I tried**
- Turned everything off and then back on (sometimes it works 😊)
- Reinstall Android 9.0 on Android Studio
- Wipe the phone with Android 9.0
- Create a new phone with Android 9.0
- Delete node modules and build folders, then npm and rebuild
- Tried a few graddle configs suggested on StackOverflow or in the issues on github (such as https://github.com/nitaliano/react-native-mapbox-gl/issues/1139#issuecomment-379647942 or https://github.com/react-native-mapbox-gl/maps/issues/626)

**My configuration**

- Platform: ios (works), Android (fail only on 9.0)
- Emulator/ Simulator: simulator except Android 7.0 on real device
- react-native-mapbox-gl: ^8.0.0-rc5
- React Native Version: 0.61.5
- Android Studio Version: 3.6.1
- Config for SDK:
![Screen Shot 2020-04-10 at 1 12 17 PM](https://user-images.githubusercontent.com/6892852/79009225-0a03fe00-7b2d-11ea-9cb9-85ccbf465cfd.png)
![Screen Shot 2020-04-10 at 1 12 26 PM](https://user-images.githubusercontent.com/6892852/79009235-0e301b80-7b2d-11ea-8413-560eef1450c0.png)
![Screen Shot 2020-04-10 at 1 12 32 PM](https://user-images.githubusercontent.com/6892852/79009248-138d6600-7b2d-11ea-9f86-7e2881ec63b6.png)
- Config for AVD
![Screen Shot 2020-04-10 at 1 12 47 PM](https://user-images.githubusercontent.com/6892852/79009267-2011be80-7b2d-11ea-8cb3-3cda7bd66f74.png)

**Test screenshot**

From left to right:
- ios
- Android 10.0
- Android 8.1
- Android 9 (crashed so I could only get access to the app by using the launchpad)

![Screen Shot 2020-04-10 at 1 16 22 PM](https://user-images.githubusercontent.com/6892852/79009564-b9d96b80-7b2d-11ea-92e0-0aff69dbb2d6.png)

**Comment by mfazekas** [comment]
@GGrassiant this looks like #737.

Please try the workaround suggested here:
https://github.com/react-native-mapbox-gl/maps/issues/737#issuecomment-607797126

**Comment by mfazekas** [comment]
Duplicate: #737

**Comment by GGrassiant** [comment]
@mfazekas Wow thanks a lot for the swift feedback!
It worked :)
I spent so many hours reading so many threads I don't know why I did not see it! Sorry for opening a duplicate.
Thanks a lot :)
