### ISSUE TITLE
Error while updating property 'stop' of a view managed by: RCTMGLCamera

### ISSUE THREAD

**Issue by bscheideldyrt** [react-native-mapbox-gl/maps#862]
**Describe the bug**

Fatal crash received from Sentry.

**To Reproduce**

NullPointerException
Attempt to read from null array

```
box.mapboxsdk.maps.Projection in getContentPadding at line 44
com.mapbox.mapboxsdk.maps.MapboxMap in getPadding at line 1611
com.mapbox.rctmgl.components.camera.CameraStop in toCameraUpdate at line 98
com.mapbox.rctmgl.components.camera.CameraUpdateQueue in execute at line 67
com.mapbox.rctmgl.components.camera.RCTMGLCamera in updateCamera at line 207
com.mapbox.rctmgl.components.camera.RCTMGLCamera in setStop at line 159
com.mapbox.rctmgl.components.camera.RCTMGLCameraManager in setStop at line 44
```

**Expected behavior**
No crash.

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Samsung SM-N950U
 - Emulator/ Simulator: No
 - OS: Android 8.0.0
 - react-native-mapbox-gl Version: 8.0.0
 - React Native Version 0.61.4

**Additional context**

**Comment by ilsuocero** [comment]
I have the same issue. Did you move forward?

**Comment by bscheideldyrt** [comment]
@ilsuocero No, we're still seeing this crash.

**Comment by mfazekas** [comment]
Can you reproduce the issue, can you attach a component to reproduce the issue?!

**Comment by bscheideldyrt** [comment]
No, just seeing consistent crash reports in Sentry.  We've never been able to reproduce this issue in our testing.  Here's a more complete stack trace, but that's all I have.  We've seen about 50 crashes from this one in the past week.  

Can you provide any context as to what getContentPadding is doing so that we have more info to try and reproduce?

```
java.lang.NullPointerException: Attempt to read from null array
    at com.mapbox.mapboxsdk.maps.Projection.getContentPadding(Projection.java:44)
    at com.mapbox.mapboxsdk.maps.MapboxMap.getPadding(MapboxMap.java:1611)
    at com.mapbox.rctmgl.components.camera.CameraStop.toCameraUpdate(CameraStop.java:98)
    at com.mapbox.rctmgl.components.camera.CameraUpdateQueue.execute(CameraUpdateQueue.java:67)
    at com.mapbox.rctmgl.components.camera.RCTMGLCamera.updateCamera(RCTMGLCamera.java:207)
    at com.mapbox.rctmgl.components.camera.RCTMGLCamera.setStop(RCTMGLCamera.java:159)
    at com.mapbox.rctmgl.components.camera.RCTMGLCameraManager.setStop(RCTMGLCameraManager.java:44)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:145)
    at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:87)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
    at android.view.Choreographer.doCallbacks(Choreographer.java:797)
    at android.view.Choreographer.doFrame(Choreographer.java:728)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8016)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
java.lang.reflect.InvocationTargetException: null
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:83)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:145)
    at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:87)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
    at android.view.Choreographer.doCallbacks(Choreographer.java:797)
    at android.view.Choreographer.doFrame(Choreographer.java:728)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8016)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'stop' of a view managed by: RCTMGLCamera
    at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:98)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:134)
    at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:54)
    at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:145)
    at com.facebook.react.uimanager.UIViewOperationQueue$UpdatePropertiesOperation.execute(UIViewOperationQueue.java:87)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:779)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:888)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2200(UIViewOperationQueue.java:42)
    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:948)
    at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:28)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:174)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:84)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
    at android.view.Choreographer.doCallbacks(Choreographer.java:797)
    at android.view.Choreographer.doFrame(Choreographer.java:728)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:237)
    at android.app.ActivityThread.main(ActivityThread.java:8016)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by ilsuocero** [comment]
I move forward making many tests.
The configuration that is working is this one:

`          <MapboxGL.Camera
            ref={ref => this.camera = ref}
            zoomLevel={this.state.zoom}
            centerCoordinate={this.state.coordinates}
          />`

and for positioning the camera:

`this.camera.setCamera({
            centerCoordinate: this.state.coordinates,
            zoomLevel: this.state.zoom,
            heading: this.state.heading,  //Fix me--> rotate cursor or map 
            //animationDuration: 2000,
          })`


I hope this can help.

**Comment by bscheideldyrt** [comment]
@ilsuocero Were you able to reproduce the issue consistently?  I haven't been able to so it's unclear how to verify any potential fix.  What you are doing now looks very similar to what we were doing when we were hitting the issue.  

And it's still not clear why `getContentPadding` is blowing up.

**Comment by bscheideldyrt** [comment]
https://github.com/mapbox/mapbox-gl-native-android/issues/400

**Comment by ricardo-fadini-inventsys** [comment]
I'm getting the same issue, not sure if I'm using something after being unmounted.

**Comment by ferdicus** [comment]
We can investigate once we have viable reproduction steps. 
Can you please provide an example or repository that shows this error? 

Thanks

**Comment by ricardo-fadini-inventsys** [comment]
Sorry the delay, it happened with a customer and we've got a report through Bugsnag.
Unfortunately no one was able to reproduce the issue.
The only thing that we have for now is the stacktrace from the native side provided by Bugsnag.
We are improving our logs so if it happens again in the future we hope to have more information about how to reproduce it.

**Comment by badredaha** [comment]
Any news please ?
