### ISSUE TITLE
Trying to remove a view index above child count

### ISSUE THREAD

**Issue by priyankverma2020** [react-native-mapbox-gl/maps#874]
Hello, I am facing the Issue "trying to remove a view index above child count" on version     "@react-native-mapbox-gl/maps": "8.0.0",
 "react-native": "0.62.2"

It only fails in production mode that too only on Android devices, I feel it is arising when you mount/unmount map component very frequently.

The Error details can be found here:
    com.facebook.react.uimanager.IllegalViewOperationException: Trying to remove a view index above child count 3 view tag: 2609
     detail: View tag:2609
      children(2): [
    2593,2597,
     ],
      indicesToRemove(1): [
    3,
     ],
      tagsToDelete(1): [
    2607,
     ]
    
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:435)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:206)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:792)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:963)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by mfazekas** [comment]
@priyankverma2020 thanks for the report,

this seems to be react native related not mapbox related.

https://github.com/facebook/react-native/issues/13984
https://stackoverflow.com/questions/50022697/react-native-illegalviewoperationexception-trying-to-remove-a-view-index-above

**Comment by priyankverma2020** [comment]
@mfazekas , if i comment out the code for rendering markers, it works fine

**Comment by mfazekas** [comment]
@priyankverma2020 pls try to submit a simple reproducible example. The stack trace doesn't give any info for us.

**Comment by jaysquared** [comment]
I had some crashes like this in production on Android, but not on iOS. Turned out to be related to duplicate keys/ids. I fixed it by assigning unique ids to each annotation.

```
<MapboxGL.MarkerView
  key={annotation.uuid}
  id={annotation.uuid}
  title={annotation.locationTitle}
  coordinate={[
   annotation.coordinate.longitude,
   annotation.coordinate.latitude,
  ]}
  anchor={anchor}
  style={{ zIndex, opacity }}
 >
 {annotationComponent}
</MapboxGL.MarkerView>
```
