### ISSUE TITLE
New unhandled exception on 8.1.0 RC: Expected NUMBER but was BEGIN_ARRAY at path $.coordinates[0]

### ISSUE THREAD

**Issue by bscheideldyrt** [react-native-mapbox-gl/maps#918]
**Describe the bug**
We're seeing a new unhandled exception in Mapbox geojson on Android on the latest release.  Seems to occur only when a phone is waking up and foregrounding the app.

```
java.lang.IllegalStateException: Expected NUMBER but was BEGIN_ARRAY at path $.coordinates[0]
    at com.google.gson.internal.bind.JsonTreeReader.nextDouble
    at com.mapbox.geojson.BaseCoordinatesTypeAdapter.readPointList
    at com.mapbox.geojson.ListOfDoublesCoordinatesTypeAdapter.read
    at com.mapbox.geojson.ListOfDoublesCoordinatesTypeAdapter.read
    at com.mapbox.geojson.BaseGeometryTypeAdapter.readCoordinateContainer
    at com.mapbox.geojson.Point$GsonTypeAdapter.read
    at com.mapbox.geojson.Point$GsonTypeAdapter.read
    at com.google.gson.TypeAdapter.fromJsonTree
    at com.google.gson.typeadapters.RuntimeTypeAdapterFactory$1.read
    at com.google.gson.TypeAdapter$1.read
    at com.mapbox.geojson.Feature$GsonTypeAdapter.read
    at com.mapbox.geojson.Feature$GsonTypeAdapter.read
    at com.google.gson.Gson.fromJson
    at com.google.gson.Gson.fromJson
    at com.google.gson.Gson.fromJson
    at com.google.gson.Gson.fromJson
    at com.mapbox.geojson.Feature.fromJson
    at a.n.d.f.e.q
    at a.n.d.c.d.a.a
    at com.mapbox.rctmgl.components.camera.RCTMGLCameraManager.setStop
    at java.lang.reflect.Method.invoke(Method.java)
    at a.h.d1.l0.o0.a
    at com.facebook.react.uimanager.ViewManager.updateProperties
    at a.h.d1.l0.h.a
    at a.h.d1.l0.k0$u.execute
    at a.h.d1.l0.k0$a.run
    at a.h.d1.l0.k0.a
    at a.h.d1.l0.k0$i.b
    at a.h.d1.l0.a.a
    at a.h.d1.h0.c.f$c.a
    at a.h.d1.h0.c.a.doFrame
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
    at android.view.Choreographer.doCallbacks(Choreographer.java:791)
    at android.view.Choreographer.doFrame(Choreographer.java:722)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7356)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**To Reproduce**
Steps to reproduce the behavior. 

No reliable way to reproduce at this time.  

**Expected behavior**
No crash.

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Multiple
 - Emulator/ Simulator: No
 - OS: Android 8.10, 9, 10
 - react-native-mapbox-gl Version 8.1.0 RC 1
 - React Native Version 61.3

**Additional context**
We're seeing new Sentry logs for this issue after a release.

**Comment by mfazekas** [comment]
@bscheideldyrt thanks for the report, 

The issue might come from here:

https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java#L135

Do you pass `centerCoordinate` to some camera operation?! Are you sure it's always valid?! Mesage suggest that instead of centerCoordinate={[-74.126410, 40.797968]} it was called with centerCoordinate={[[-74.126410, 40.797968]]}


I'm closing this not because it's solved, but because it's not really actionable without figuring out if it's an app error (invalid stuff passed to camera update in some cases) or library issue.
