### ISSUE TITLE
Crash on removing draw

### ISSUE THREAD

**Issue by mahipalsingh7** [react-native-mapbox-gl/maps#927]
` E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 16981
    java.lang.Error: Cannot remove detached source
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRemoveSource(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.removeSource(NativeMapView.java:925)
        at com.mapbox.mapboxsdk.maps.Style.removeSource(Style.java:175)
        at com.mapbox.rctmgl.components.styles.sources.RCTSource.removeFromMap(RCTSource.java:158)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.removeFeature(RCTMGLMapView.java:277)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.removeViewAt(RCTMGLMapViewManager.java:92)
        at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.removeViewAt(RCTMGLMapViewManager.java:39)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:458)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:206)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:792)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:903)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2400(UIViewOperationQueue.java:43)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:963)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1083)
        at android.view.Choreographer.doCallbacks(Choreographer.java:908)
        at android.view.Choreographer.doFrame(Choreographer.java:831)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1070)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7782)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
`

**Comment by mfazekas** [comment]
crash coming from here:
https://github.com/mapbox/mapbox-gl-native-android/blob/b16d47ce03804bc8b50f6469a48be51b4a580b78/MapboxGLAndroidSDK/src/cpp/style/sources/source.cpp#L174-L185

@mahipalsingh7 the report missing versions and a sample component to reproduce the issue.
